/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiTerminalStreamRouteImport } from './routes/api/terminal-stream'
import { Route as ApiTerminalResizeRouteImport } from './routes/api/terminal-resize'
import { Route as ApiTerminalInputRouteImport } from './routes/api/terminal-input'
import { Route as ApiTerminalCloseRouteImport } from './routes/api/terminal-close'
import { Route as ApiSkillsRouteImport } from './routes/api/skills'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSessionStatusRouteImport } from './routes/api/session-status'
import { Route as ApiSendStreamRouteImport } from './routes/api/send-stream'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPathsRouteImport } from './routes/api/paths'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiHermesJobsRouteImport } from './routes/api/hermes-jobs'
import { Route as ApiHermesConfigRouteImport } from './routes/api/hermes-config'
import { Route as ApiGatewayStatusRouteImport } from './routes/api/gateway-status'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as ApiContextUsageRouteImport } from './routes/api/context-usage'
import { Route as ApiChatEventsRouteImport } from './routes/api/chat-events'
import { Route as ApiAuthCheckRouteImport } from './routes/api/auth-check'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiSessionsSendRouteImport } from './routes/api/sessions/send'
import { Route as ApiMemoryWriteRouteImport } from './routes/api/memory/write'
import { Route as ApiMemorySearchRouteImport } from './routes/api/memory/search'
import { Route as ApiMemoryReadRouteImport } from './routes/api/memory/read'
import { Route as ApiMemoryListRouteImport } from './routes/api/memory/list'
import { Route as ApiHermesJobsJobIdRouteImport } from './routes/api/hermes-jobs.$jobId'
import { Route as ApiSessionsSessionKeyStatusRouteImport } from './routes/api/sessions/$sessionKey.status'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalStreamRoute = ApiTerminalStreamRouteImport.update({
  id: '/api/terminal-stream',
  path: '/api/terminal-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalResizeRoute = ApiTerminalResizeRouteImport.update({
  id: '/api/terminal-resize',
  path: '/api/terminal-resize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalInputRoute = ApiTerminalInputRouteImport.update({
  id: '/api/terminal-input',
  path: '/api/terminal-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTerminalCloseRoute = ApiTerminalCloseRouteImport.update({
  id: '/api/terminal-close',
  path: '/api/terminal-close',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSkillsRoute = ApiSkillsRouteImport.update({
  id: '/api/skills',
  path: '/api/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionStatusRoute = ApiSessionStatusRouteImport.update({
  id: '/api/session-status',
  path: '/api/session-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendStreamRoute = ApiSendStreamRouteImport.update({
  id: '/api/send-stream',
  path: '/api/send-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPathsRoute = ApiPathsRouteImport.update({
  id: '/api/paths',
  path: '/api/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsRoute = ApiHermesJobsRouteImport.update({
  id: '/api/hermes-jobs',
  path: '/api/hermes-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesConfigRoute = ApiHermesConfigRouteImport.update({
  id: '/api/hermes-config',
  path: '/api/hermes-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGatewayStatusRoute = ApiGatewayStatusRouteImport.update({
  id: '/api/gateway-status',
  path: '/api/gateway-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContextUsageRoute = ApiContextUsageRouteImport.update({
  id: '/api/context-usage',
  path: '/api/context-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatEventsRoute = ApiChatEventsRouteImport.update({
  id: '/api/chat-events',
  path: '/api/chat-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckRoute = ApiAuthCheckRouteImport.update({
  id: '/api/auth-check',
  path: '/api/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSendRoute = ApiSessionsSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiSessionsRoute,
} as any)
const ApiMemoryWriteRoute = ApiMemoryWriteRouteImport.update({
  id: '/api/memory/write',
  path: '/api/memory/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemorySearchRoute = ApiMemorySearchRouteImport.update({
  id: '/api/memory/search',
  path: '/api/memory/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryReadRoute = ApiMemoryReadRouteImport.update({
  id: '/api/memory/read',
  path: '/api/memory/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryListRoute = ApiMemoryListRouteImport.update({
  id: '/api/memory/list',
  path: '/api/memory/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHermesJobsJobIdRoute = ApiHermesJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiHermesJobsRoute,
} as any)
const ApiSessionsSessionKeyStatusRoute =
  ApiSessionsSessionKeyStatusRouteImport.update({
    id: '/$sessionKey/status',
    path: '/$sessionKey/status',
    getParentRoute: () => ApiSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/files': typeof FilesRoute
  '/jobs': typeof JobsRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/skills': typeof SkillsRoute
  '/terminal': typeof TerminalRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/auth-check': typeof ApiAuthCheckRoute
  '/api/chat-events': typeof ApiChatEventsRoute
  '/api/context-usage': typeof ApiContextUsageRoute
  '/api/files': typeof ApiFilesRoute
  '/api/gateway-status': typeof ApiGatewayStatusRoute
  '/api/hermes-config': typeof ApiHermesConfigRoute
  '/api/hermes-jobs': typeof ApiHermesJobsRouteWithChildren
  '/api/history': typeof ApiHistoryRoute
  '/api/models': typeof ApiModelsRoute
  '/api/paths': typeof ApiPathsRoute
  '/api/send': typeof ApiSendRoute
  '/api/send-stream': typeof ApiSendStreamRoute
  '/api/session-status': typeof ApiSessionStatusRoute
  '/api/sessions': typeof ApiSessionsRouteWithChildren
  '/api/skills': typeof ApiSkillsRoute
  '/api/terminal-close': typeof ApiTerminalCloseRoute
  '/api/terminal-input': typeof ApiTerminalInputRoute
  '/api/terminal-resize': typeof ApiTerminalResizeRoute
  '/api/terminal-stream': typeof ApiTerminalStreamRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/hermes-jobs/$jobId': typeof ApiHermesJobsJobIdRoute
  '/api/memory/list': typeof ApiMemoryListRoute
  '/api/memory/read': typeof ApiMemoryReadRoute
  '/api/memory/search': typeof ApiMemorySearchRoute
  '/api/memory/write': typeof ApiMemoryWriteRoute
  '/api/sessions/send': typeof ApiSessionsSendRoute
  '/api/sessions/$sessionKey/status': typeof ApiSessionsSessionKeyStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/context-usage'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/models'
    | '/api/paths'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/hermes-jobs/$jobId'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/sessions/send'
    | '/api/sessions/$sessionKey/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/skills'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/context-usage'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/models'
    | '/api/paths'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/providers'
    | '/chat'
    | '/settings'
    | '/api/hermes-jobs/$jobId'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/sessions/send'
    | '/api/sessions/$sessionKey/status'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/files'
    | '/jobs'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/terminal'
    | '/api/auth'
    | '/api/auth-check'
    | '/api/chat-events'
    | '/api/context-usage'
    | '/api/files'
    | '/api/gateway-status'
    | '/api/hermes-config'
    | '/api/hermes-jobs'
    | '/api/history'
    | '/api/models'
    | '/api/paths'
    | '/api/send'
    | '/api/send-stream'
    | '/api/session-status'
    | '/api/sessions'
    | '/api/skills'
    | '/api/terminal-close'
    | '/api/terminal-input'
    | '/api/terminal-resize'
    | '/api/terminal-stream'
    | '/api/workspace'
    | '/chat/$sessionKey'
    | '/settings/providers'
    | '/chat/'
    | '/settings/'
    | '/api/hermes-jobs/$jobId'
    | '/api/memory/list'
    | '/api/memory/read'
    | '/api/memory/search'
    | '/api/memory/write'
    | '/api/sessions/send'
    | '/api/sessions/$sessionKey/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  FilesRoute: typeof FilesRoute
  JobsRoute: typeof JobsRoute
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SkillsRoute: typeof SkillsRoute
  TerminalRoute: typeof TerminalRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiAuthCheckRoute: typeof ApiAuthCheckRoute
  ApiChatEventsRoute: typeof ApiChatEventsRoute
  ApiContextUsageRoute: typeof ApiContextUsageRoute
  ApiFilesRoute: typeof ApiFilesRoute
  ApiGatewayStatusRoute: typeof ApiGatewayStatusRoute
  ApiHermesConfigRoute: typeof ApiHermesConfigRoute
  ApiHermesJobsRoute: typeof ApiHermesJobsRouteWithChildren
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiPathsRoute: typeof ApiPathsRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSendStreamRoute: typeof ApiSendStreamRoute
  ApiSessionStatusRoute: typeof ApiSessionStatusRoute
  ApiSessionsRoute: typeof ApiSessionsRouteWithChildren
  ApiSkillsRoute: typeof ApiSkillsRoute
  ApiTerminalCloseRoute: typeof ApiTerminalCloseRoute
  ApiTerminalInputRoute: typeof ApiTerminalInputRoute
  ApiTerminalResizeRoute: typeof ApiTerminalResizeRoute
  ApiTerminalStreamRoute: typeof ApiTerminalStreamRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiMemoryListRoute: typeof ApiMemoryListRoute
  ApiMemoryReadRoute: typeof ApiMemoryReadRoute
  ApiMemorySearchRoute: typeof ApiMemorySearchRoute
  ApiMemoryWriteRoute: typeof ApiMemoryWriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-stream': {
      id: '/api/terminal-stream'
      path: '/api/terminal-stream'
      fullPath: '/api/terminal-stream'
      preLoaderRoute: typeof ApiTerminalStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-resize': {
      id: '/api/terminal-resize'
      path: '/api/terminal-resize'
      fullPath: '/api/terminal-resize'
      preLoaderRoute: typeof ApiTerminalResizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-input': {
      id: '/api/terminal-input'
      path: '/api/terminal-input'
      fullPath: '/api/terminal-input'
      preLoaderRoute: typeof ApiTerminalInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terminal-close': {
      id: '/api/terminal-close'
      path: '/api/terminal-close'
      fullPath: '/api/terminal-close'
      preLoaderRoute: typeof ApiTerminalCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/skills': {
      id: '/api/skills'
      path: '/api/skills'
      fullPath: '/api/skills'
      preLoaderRoute: typeof ApiSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session-status': {
      id: '/api/session-status'
      path: '/api/session-status'
      fullPath: '/api/session-status'
      preLoaderRoute: typeof ApiSessionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-stream': {
      id: '/api/send-stream'
      path: '/api/send-stream'
      fullPath: '/api/send-stream'
      preLoaderRoute: typeof ApiSendStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paths': {
      id: '/api/paths'
      path: '/api/paths'
      fullPath: '/api/paths'
      preLoaderRoute: typeof ApiPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs': {
      id: '/api/hermes-jobs'
      path: '/api/hermes-jobs'
      fullPath: '/api/hermes-jobs'
      preLoaderRoute: typeof ApiHermesJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-config': {
      id: '/api/hermes-config'
      path: '/api/hermes-config'
      fullPath: '/api/hermes-config'
      preLoaderRoute: typeof ApiHermesConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gateway-status': {
      id: '/api/gateway-status'
      path: '/api/gateway-status'
      fullPath: '/api/gateway-status'
      preLoaderRoute: typeof ApiGatewayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/context-usage': {
      id: '/api/context-usage'
      path: '/api/context-usage'
      fullPath: '/api/context-usage'
      preLoaderRoute: typeof ApiContextUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-events': {
      id: '/api/chat-events'
      path: '/api/chat-events'
      fullPath: '/api/chat-events'
      preLoaderRoute: typeof ApiChatEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-check': {
      id: '/api/auth-check'
      path: '/api/auth-check'
      fullPath: '/api/auth-check'
      preLoaderRoute: typeof ApiAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/send': {
      id: '/api/sessions/send'
      path: '/send'
      fullPath: '/api/sessions/send'
      preLoaderRoute: typeof ApiSessionsSendRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
    '/api/memory/write': {
      id: '/api/memory/write'
      path: '/api/memory/write'
      fullPath: '/api/memory/write'
      preLoaderRoute: typeof ApiMemoryWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/search': {
      id: '/api/memory/search'
      path: '/api/memory/search'
      fullPath: '/api/memory/search'
      preLoaderRoute: typeof ApiMemorySearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/read': {
      id: '/api/memory/read'
      path: '/api/memory/read'
      fullPath: '/api/memory/read'
      preLoaderRoute: typeof ApiMemoryReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/list': {
      id: '/api/memory/list'
      path: '/api/memory/list'
      fullPath: '/api/memory/list'
      preLoaderRoute: typeof ApiMemoryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hermes-jobs/$jobId': {
      id: '/api/hermes-jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/hermes-jobs/$jobId'
      preLoaderRoute: typeof ApiHermesJobsJobIdRouteImport
      parentRoute: typeof ApiHermesJobsRoute
    }
    '/api/sessions/$sessionKey/status': {
      id: '/api/sessions/$sessionKey/status'
      path: '/$sessionKey/status'
      fullPath: '/api/sessions/$sessionKey/status'
      preLoaderRoute: typeof ApiSessionsSessionKeyStatusRouteImport
      parentRoute: typeof ApiSessionsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface ApiHermesJobsRouteChildren {
  ApiHermesJobsJobIdRoute: typeof ApiHermesJobsJobIdRoute
}

const ApiHermesJobsRouteChildren: ApiHermesJobsRouteChildren = {
  ApiHermesJobsJobIdRoute: ApiHermesJobsJobIdRoute,
}

const ApiHermesJobsRouteWithChildren = ApiHermesJobsRoute._addFileChildren(
  ApiHermesJobsRouteChildren,
)

interface ApiSessionsRouteChildren {
  ApiSessionsSendRoute: typeof ApiSessionsSendRoute
  ApiSessionsSessionKeyStatusRoute: typeof ApiSessionsSessionKeyStatusRoute
}

const ApiSessionsRouteChildren: ApiSessionsRouteChildren = {
  ApiSessionsSendRoute: ApiSessionsSendRoute,
  ApiSessionsSessionKeyStatusRoute: ApiSessionsSessionKeyStatusRoute,
}

const ApiSessionsRouteWithChildren = ApiSessionsRoute._addFileChildren(
  ApiSessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  FilesRoute: FilesRoute,
  JobsRoute: JobsRoute,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SkillsRoute: SkillsRoute,
  TerminalRoute: TerminalRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiAuthCheckRoute: ApiAuthCheckRoute,
  ApiChatEventsRoute: ApiChatEventsRoute,
  ApiContextUsageRoute: ApiContextUsageRoute,
  ApiFilesRoute: ApiFilesRoute,
  ApiGatewayStatusRoute: ApiGatewayStatusRoute,
  ApiHermesConfigRoute: ApiHermesConfigRoute,
  ApiHermesJobsRoute: ApiHermesJobsRouteWithChildren,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiPathsRoute: ApiPathsRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSendStreamRoute: ApiSendStreamRoute,
  ApiSessionStatusRoute: ApiSessionStatusRoute,
  ApiSessionsRoute: ApiSessionsRouteWithChildren,
  ApiSkillsRoute: ApiSkillsRoute,
  ApiTerminalCloseRoute: ApiTerminalCloseRoute,
  ApiTerminalInputRoute: ApiTerminalInputRoute,
  ApiTerminalResizeRoute: ApiTerminalResizeRoute,
  ApiTerminalStreamRoute: ApiTerminalStreamRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiMemoryListRoute: ApiMemoryListRoute,
  ApiMemoryReadRoute: ApiMemoryReadRoute,
  ApiMemorySearchRoute: ApiMemorySearchRoute,
  ApiMemoryWriteRoute: ApiMemoryWriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
